# - The value 'placeholder-repo' is a sample. Please replace it with your actual image repository for production use.
image:
  repository: placeholder-repo
  tag: latest
  pullPolicy: Never

service:
  type: ClusterIP
  port: 3000